owner: mattdigital-dev
repo: katacode-status

sites:
  - name: Web Platform
    url: https://katacode.fr

  - name: API
    url: https://api.katacode.fr/api/health

  - name: Auth
    url: https://api.katacode.fr/api/health/auth

  - name: Database
    url: https://api.katacode.fr/api/health/database

  - name: Redis
    url: https://api.katacode.fr/api/health/redis

  - name: Storage (S3)
    url: https://api.katacode.fr/api/health/s3

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.katacode.fr
  name: Status KataCode
  introTitle: "Statut des services KataCode"
  introMessage: "Surveillance automatisée toutes les 5 minutes via GitHub Actions."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
